language: c

sudo: false

cache:
  directories:
  - $HOME/.racket/download-cache

env:
- PATH=~/racket/bin:$PATH

addons:
 apt:
  packages:
   - tree

os:
- linux

before_install:
- export PKG=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`
- echo $PKG
- curl -L -o installer.sh http://plt.eecs.northwestern.edu/snapshots/current/installers/min-racket-current-x86_64-linux-precise.sh
- sh installer.sh --in-place --dest ~/racket/
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"

install:
- raco pkg install -i --deps search-auto compiler-lib # for `raco test`
- racket -l- pkg/dirs-catalog --link --check-metadata pkgs-catalog .
- ls -l pkgs-catalog/pkg/
- cat pkgs-catalog/pkg/*
- tree pkgs-catalog/
- echo file://`pwd`/pkgs-catalog/ > catalog-config.txt
- raco pkg config catalogs >> catalog-config.txt
- cat catalog-config.txt
- raco pkg config -i --set catalogs `cat catalog-config.txt`
- raco pkg config -i
- raco pkg install --no-setup -i --deps search-auto $PKG-lib $PKG-test
- ls $HOME/.racket/download-cache


script:
- raco setup -D
- raco test -p $PKG-lib
- raco test -p $PKG-test
